 <?php
 use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
require_once 'GoogleAuthenticator.php';

$ga = new GoogleAuthenticator();

$qrCodeUrl = $ga->getQRCodeGoogleUrl($email, $secret,'system.bitway.org');
//echo $qrCodeUrl;exit;



?>
<!DOCTYPE html>
<html>
<head>
<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js" type="text/javascript"></script>

    <title>2-Step Verification using Google Authenticator</title>
</head>
<body>
	<div id="container" style="text-align: center;color: #ffffff;">
		<h1>2-Step Verification using Google Authenticator</h1>
		<divm id='device'>

<!-- start -->
<body class="login-layout">
<div class="container">
<div class="form-box2">
<div class="login-boxs col-md-3">
<h1 class="text-center">
<img src="<?php echo $qrCodeUrl; ?>" alt="bitway">
</h1>


<div class="form-group field-loginform-username required">
	<input type="text" id="code" class="form-control" name="code" placeholder="Enter Google Authentication Code" >
	<span id="error_code" style="display:none;color:red;">Enter Google Code</span>
</div>

<div class="form-group">
	<button type="button" class="btn btn-primary form-control" name="verify_code" id="verify_code">Verify</button> </div>
	<div style="clear: both"></div>
</div>

</div>
</div>
<p>Enter the verification code generated by Google Authenticator app on your phone.</p>
</div>
</div>
<script>

$("#verify_code").on('click',function(){
	var code = $("#code").val();
	if(code==''){
		$("#error_code").show();
	}else{
		$("#error_code").hide();
		$.ajax({
        type: "POST", 
        url:'/site/checkcode', 
        data: {code:code},
        success: function (data) {
          if(data==1){
			 
               window.location.href = 'https://system.bitway.org/';
          }else if(data==0){
			  $("#error_code").show();
			  $("#error_code").html('Enter Vali Google Authentication Code');
		  }
        }
    });
	}
});
</script>
</body>
</html>
